# Generated by Django 6.0.7 on 2026-07-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='produk/')),
                ('diskon', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
