# Generated by Django 6.0.7 on 2026-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Diproses', 'Diproses'), ('Dikirim', 'Dikirim'), ('Selesai', 'Selesai')], default='Menunggu Pembayaran', max_length=30),
        ),
    ]
