# Generated by Django 6.0.7 on 2026-07-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subjek',
        ),
    ]
